// This file is auto-generated by scripts/sync-changelog.mjs
// Do not edit manually.

export type ReleaseEntry = {
  version: string
  date: string
  title: string
  summary: string
  highlights: string[]
}

export type TimelineRow = {
  version: string
  date: string
  title: string
}

export const changelogGeneratedAt = "2026-03-28T05:58:57.712Z"

export const recentReleases: ReleaseEntry[] = [
  {
    "version": "1.8.9",
    "date": "2026-03-26",
    "title": "OSS Pressure Containment and Operational Truth Alignment",
    "summary": "---",
    "highlights": [
      "RFC-0011 OSS pressure containment (@tracehound/core): Added deterministic pressure state transitions (normal | elevated | critical), bounded threshold configuration, runtime pressure observation, and critical-mode archive suppression for TTL decay paths. Pressure is now exposed as a first-class runtime signal via watcher snapshots, system snapshots, CLI surfaces, and notification events.",
      "Pressure hysteresis and saturation correctness (@tracehound/core): Hardened Hound pressure recovery behavior so cooldown is honored, added count-based saturation tracking alongside byte capacity, and corrected default threshold normalization for high elevatedWatermark values and fractional cooldown inputs.",
      "Snapshot compatibility and health derivation (@tracehound/core, @tracehound/cli): Signed snapshots produced by older versions remain readable; missing pressure fields are normalized to a safe default state on read. System health derivation now keeps Hound pool exhaustion at critical precedence even when pressure mode is only elevated.",
      "Operator pressure visibility (@tracehound/cli): Human-readable status output now includes archive-failure pressure telemetry, aligning terminal output with the existing JSON snapshot surface.",
      "RFC and docs alignment: Updated RFC-0000 Hound/IPC wording to match the shipped child-process + framed stdio implementation, marked implemented RFCs consistently, and completed RFC-0011 OSS-scope implementation notes.",
      "Configuration and API docs: Added pressure configuration guidance, enforced threshold-ordering invariants, trace-id signaling/inspect workflow updates, and refreshed API/config references to match the current runtime.",
      "No breaking public API changes.",
      "Existing deployments can adopt pressure thresholds incrementally; hard caps and fail-open semantics remain unchanged."
    ]
  },
  {
    "version": "1.8.8",
    "date": "2026-03-25",
    "title": "Adapter Security Hardening and Zero-Dependency Core",
    "summary": "option added to both adapters. When Content-Length exceeds the configured limit the body clone (JSON.stringify + JSON.parse) is skipped before agent.intercept() is called, preventing adversarial oversized payloads from causing 2–3× peak memory pressure. ingressBytes (rawBody) is still captured for deterministic signature computation. option allows deployments behind a CDN or load balancer to override req.ip (which follows the framework's trust proxy setting) with a trusted source such as req.socket.remoteAddress. A misconfigured trust-proxy deployment allows X-Forwarded-For spoofing to exhaust a victim's rate-limit budget — this option closes that gap. (e.g. /path?foo=bar), causing the same data to appear in both the path and query fields of every captured scent. Fixed with indexOf-based path extraction, consistent with Express req.path. non-standard per RFC 7230 §3.2.2 and may indicate header injection or request smuggling. The adapter now takes the first value as the canonical source and adds an x-multiple-user-agents: true forensic flag to the captured headers when duplicates are present. pnpm.overrides: { \"flatted\": \">=3.4.2\" }. Affected the eslint → file-entry-cache → flat-cache → flatted chain only. Production builds were unaffected. manager used across all CI workflows. Node.js built-in crypto.randomUUID() + crypto.randomBytes(). generateSecureId() output format is unchanged ({uuidv4}-{8 hex chars}); isValidSecureId() continues to validate the same format. @tracehound/core now has zero runtime dependencies. targets and is tested against Fastify v5. Updated to ^5.0.0. maxPayloadSize, resolveSourceIp, emitSignatureInResponse, emitTraceIdHeader, extractScent, and onIntercept with security rationale for each option. unaffected. Both options are strongly recommended for production use behind a proxy or CDN. ---",
    "highlights": [
      "Memory amplification prevention (@tracehound/express, @tracehound/fastify): New maxPayloadSize",
      "IP spoofing / rate-limit bypass (@tracehound/express, @tracehound/fastify): New resolveSourceIp",
      "Fastify duplicate path+query in Scent (@tracehound/fastify): req.url includes the query string",
      "Multi-value User-Agent handling (@tracehound/fastify): Multiple User-Agent headers are",
      "flatted prototype pollution (dev dependency chain): Patched GHSA-rf6f-7fwh-wjgh via",
      "pnpm upgrade 9.1.4 → 10.33.0: Addresses CVE-2024-53866 and CVE-2025-69262 in the package",
      "Zero runtime dependencies in @tracehound/core: Replaced the uuid runtime dependency with",
      "Fastify peerDependency mismatch: fastify peer was declared as ^4.0.0 but the package"
    ]
  },
  {
    "version": "1.8.7",
    "date": "2026-03-18",
    "title": "Evidence Ownership Hardening and Test Type Safety",
    "summary": "Previously the constructor stored the caller's buffer by reference; any code retaining the original reference could silently mutate forensic bytes after the one-time hash check, bypassing tamper detection entirely. The owned copy is now created first (bytes.slice(0)), and the hash is verified against that copy — closing the post-construction mutation window. allocating a defensive copy. The public bytes getter continues to return a copy on every call (required for external callers). HoundPool IPC send (_send) now uses _bytesRef to avoid a redundant allocation per evidence dispatch in the hot path. original buffer after construction\" — verifies that filling the caller-retained buffer with 0xde bytes after construction does not alter the evidence's stored bytes. import type. exactOptionalPropertyTypes violations resolved — npx tsc -p tsconfig.tests.json --noEmit now exits clean. continue using evidence.bytes.",
    "highlights": [
      "Evidence constructor now copies the caller-provided ArrayBuffer before hashing and storing it.",
      "Added Evidence._bytesRef internal getter that returns the raw buffer reference without",
      "Regression test added to evidence.test.ts: \"should not be affected by caller mutating the",
      "Fixed remaining TypeScript strict-mode errors across the test suite (tsconfig.tests.json):",
      "All previously failing noUncheckedIndexedAccess, noPropertyAccessFromIndexSignature, and",
      "No breaking changes to the public API.",
      "No configuration contract changes.",
      "Evidence._bytesRef is an internal getter (underscore-prefixed); external consumers should"
    ]
  },
  {
    "version": "1.8.6",
    "date": "2026-03-12",
    "title": "Package README Modernization (Docs-Only)",
    "summary": "This patch release refreshes stale package-level documentation and aligns examples with the current public API and runtime behavior. No runtime code paths or package contracts were changed.",
    "highlights": [
      "packages/core/README.md: Rewritten around the current createTracehound flow, Scent contract (source object + threat signal + optional ingressBytes), intercept statuses, and signed snapshot integration.",
      "packages/express/README.md: Updated middleware options and behavior docs (emitTraceIdHeader, fail-open mapping, deterministic rawBody guidance, and onIntercept pattern).",
      "packages/fastify/README.md: Updated plugin options and behavior docs (emitTraceIdHeader, fail-open mapping, deterministic req.rawBody requirement, and onIntercept pattern).",
      "packages/cli/README.md: Expanded CLI command reference (status, stats, inspect, watch, history clear, disk clear) plus required snapshot env inputs and trace-inspection workflow.",
      "packages/core/scenarios/README.md: Replaced outdated scenario notes with current scenario suite and execution commands.",
      "No breaking changes.",
      "No runtime behavior changes.",
      "No configuration contract changes."
    ]
  },
  {
    "version": "1.8.5",
    "date": "2026-03-12",
    "title": "CLI Dashboard Overhaul, Soak Infrastructure, and Fix Wave",
    "summary": "CLI Dashboard Overhaul, Soak Infrastructure, and Fix Wave",
    "highlights": [
      "CLI watch dashboard overhaul (packages/cli): Redesigned multi-screen ANSI live dashboard (watch.ts) with bold values, colon-separated key/value labels, and consistent color hierarchy via theme utilities. Screens: overview, watcher, quarantine, pool, agent, help. Nav keys: [1–5], [h], [r], [q]. Command bar pinned to terminal bottom row in TTY mode.",
      "format.ts consolidation (packages/cli): Merged fmt.ts into format.ts as the single canonical formatting module — fmtBytes, fmtCount, fmtDuration, fmtStatus, fmtUptime.",
      "Soak load-test infrastructure (infrastructure/soak): Moved soak harness from packages/ to infrastructure/soak; added server.ts, audit.ts, file-cold-storage.ts, metrics.ts, traffic.ts, main.ts. Updated pnpm-workspace.yaml accordingly.",
      "CLI watch command exposed via src/index.ts.",
      "startDashboard setInterval regression (packages/cli): Removed the early-return guard on !process.stdout.isTTY that prevented setInterval from being registered. Replaced process.stdin.isTTY checks with typeof process.stdin.setRawMode === 'function' so raw-mode setup and key-navigation work correctly in all environments.",
      "refreshMs unit inconsistency (packages/cli): Removed erroneous Math.ceil(refreshMs / 1000) conversion in startDashboard and renderDashboard; the overview header was displaying refresh: 1ms instead of refresh: 1000ms.",
      "Last-alert field label renamed from \"id\" to \"signature\" in the LAST ALERT DETAIL section to match the actual field name and domain terminology.",
      "renderScreen void returns: Removed return statements from void renderScreen switch branches."
    ]
  }
]

export const timelineRows: TimelineRow[] = [
  {
    "version": "1.8.4",
    "date": "2026-03-11",
    "title": "Post-1.8.3 Workflow and Security Maintenance Patch"
  },
  {
    "version": "1.8.3",
    "date": "2026-03-11",
    "title": "ESLint Clock/RNG SSoT, Monotonic Evidence Timestamps, and Workflow Hardening"
  },
  {
    "version": "1.8.2",
    "date": "2026-03-10",
    "title": "Security Hardening and Remediation Closure Wave"
  },
  {
    "version": "1.8.1",
    "date": "N/A",
    "title": "Security QA & Docs Alignment"
  },
  {
    "version": "1.8.0",
    "date": "2026-03-09",
    "title": "TLS Source Signals and Runtime Hardening"
  },
  {
    "version": "1.7.0",
    "date": "2026-03-05",
    "title": "Enhanced Quarantine Protocol and Evidence Lifecycle Hardening"
  },
  {
    "version": "1.6.1",
    "date": "2026-03-07",
    "title": "Memory Safety and Cryptographic RNG Hardening"
  },
  {
    "version": "1.6.0",
    "date": "2026-03-06",
    "title": "Operational Truth, Deterministic Analysis, and Release Readiness"
  },
  {
    "version": "1.5.0",
    "date": "2026-03-04",
    "title": "M3 Pressure Containment and Governance Delivery"
  },
  {
    "version": "1.4.4",
    "date": "2026-02-26",
    "title": "Tracehound Inline Protection Validation Harness (TIPVH) & Enterprise Hardening"
  },
  {
    "version": "1.4.3",
    "date": "2026-02-25",
    "title": "Monorepo Security Hardening & Robustness"
  },
  {
    "version": "1.4.2",
    "date": "2026-02-21",
    "title": "Document Updates & Roadmap"
  },
  {
    "version": "1.4.1",
    "date": "2026-02-21",
    "title": "Orphan Wiring & Stability Fixes"
  },
  {
    "version": "1.4.0",
    "date": "2026-02-16",
    "title": "Deterministic Fuzz Assurance Program"
  },
  {
    "version": "1.3.0",
    "date": "2026-02-16",
    "title": "Security Model Alignment & Parser Hardening"
  },
  {
    "version": "1.2.0",
    "date": "2026-02-14",
    "title": "Forensic Hardening & English Audit Prep"
  },
  {
    "version": "1.1.0",
    "date": "2026-02-10",
    "title": "Production Hardening (Phase 4 P1)"
  },
  {
    "version": "1.0.0",
    "date": "2024-12-27",
    "title": "Stable Release"
  },
  {
    "version": "0.7.0",
    "date": "N/A",
    "title": "v1.0.0 P0 Complete"
  },
  {
    "version": "0.6.0",
    "date": "N/A",
    "title": "Production Ready (P0 Complete)"
  },
  {
    "version": "0.5.0",
    "date": "N/A",
    "title": "Hound Process Isolation"
  },
  {
    "version": "0.4.0",
    "date": "N/A",
    "title": "Observability & Resilience"
  },
  {
    "version": "0.3.0",
    "date": "N/A",
    "title": "Core Logic"
  },
  {
    "version": "0.2.0",
    "date": "N/A",
    "title": "Evidence & Quarantine"
  },
  {
    "version": "0.1.0",
    "date": "N/A",
    "title": "Foundation"
  }
]
