// This file is auto-generated by scripts/sync-changelog.mjs
// Do not edit manually.

export type ReleaseEntry = {
  version: string
  date: string
  title: string
  summary: string
  highlights: string[]
}

export type TimelineRow = {
  version: string
  date: string
  title: string
}

export const changelogGeneratedAt = "2026-03-03T05:51:37.803Z"

export const recentReleases: ReleaseEntry[] = [
  {
    "version": "1.4.4",
    "date": "2026-02-26",
    "title": "Tracehound Inline Protection Validation Harness (TIPVH) & Enterprise Hardening",
    "summary": "Covers changes since commit [1.4.3 release].",
    "highlights": [
      "Tracehound Inline Protection Validation Harness (TIPVH): Engineered a complete automated adversarial testing suite containing 7 formal validation scenarios.",
      "Enterprise Multi-Target Deployment: Added Metasploitable 3 alongside Metasploitable 2 for extensive \"Vulnerability Agnostic\" proxy validation.",
      "Zero-Visibility Capability Verified: Deployed an automated GVM (OpenVAS) scanning integration yielding ZERO FINDINGS from thousands of vulnerability probes.",
      "Alternative 1: Using 3rd-party SaaS penetration testing tools. Why Rejected? Third-party tools introduce external latency variations and CI/CD egress dependency. A local, sandboxed harness (TIPVH) maintains absolute environmental control and perfect timestamp synchronization for forensic AuditChain validation without compromising the 'Single Source of Truth'."
    ]
  },
  {
    "version": "1.4.3",
    "date": "2026-02-25",
    "title": "Monorepo Security Hardening & Robustness",
    "summary": "Covers changes since commit [v1.4.2 release].",
    "highlights": [
      "Defensive Scent Extraction: Implemented safeClone in Express/Fastify adapters. This ensures the Tracehound process is resilient to circular references or exotic payload shapes (e.g., Stream objects, DOM nodes) that could otherwise trigger runtime crashes during scent extraction.",
      "Privacy Hardening: Standardized the suppression of Tracehound signature in external HTTP 403 responses by default. This reduces the adversarial correlation surface while providing an opt-in emitSignatureInResponse toggle for legitimate tracing needs.",
      "Workspace Quality Gate: Integrated root pretest and prelint hooks into package.json. These mandatory lifecycle steps enforce that @tracehound/core artifacts are compiled before workspace packages run validation, eliminating cross-package dependency resolution failures in CI.",
      "Alternative 1: Using structuredClone() for payload extraction. Why Rejected? structuredClone is strictly type-sensitive and throws on non-cloneable objects (functions, symbols). In a middleware context, we cannot trust that third-party plugins haven't attached non-serializable properties to the request. JSON-based sanitization is safer for \"High-Velocity API\" environments."
    ]
  },
  {
    "version": "1.4.2",
    "date": "2026-02-21",
    "title": "Document Updates & Roadmap",
    "summary": "Covers changes since commit 204b957d85b79f728102f37042541580953a023d. In accordance with tracehound standards, the system-wide evaluation of this release (and the format of these notes) is as follows:",
    "highlights": [
      "2026 Pilot Program (PILOT-PROGRAM-2026.md): Added vision containing go-to-market (GTM) and adoption strategies for early-stage integrators.",
      "Enhanced Quarantine Protocol (ENHANCED-QUARANTINE-PROTOCOL.md): Documented the roadmap detailing the multi-phase integration of application-level quarantine mechanisms.",
      "Resilience Edge V2 (RESILIENCE-EDGE-V2.md): Conveyed the next-generation hardware/server architecture focusing on pre-extraction protection, absolute network containment, and zero-overhead logging goals.",
      "Comprehensive Threat Model (THREAT-MODEL.md): Added an official threat model to guide future architectural decisions and strictly define security boundaries."
    ]
  },
  {
    "version": "1.4.1",
    "date": "2026-02-21",
    "title": "Orphan Wiring & Stability Fixes",
    "summary": "This patch release resolves critical architectural wiring gaps where observability and background processing components (Watcher, NotificationEmitter, HoundPool) were instantiated but disconnected from the active agent lifecycle. It also stabilizes the chaos testing suite by replacing brittle PID-based assertions with deterministic invariant checks.",
    "highlights": [
      "HoundPool Auto-Activation: Fixed a core design flaw where Agent quarantined evidence but never explicitly activated the HoundPool to process it. Agent now accepts an optional IHoundPool dependency and auto-activates workers on quarantine.",
      "Watcher Observability Wiring: Fixed Watcher remaining perpetually empty. It is now correctly wired to Agent.intercept(), receiving recordThreat(), updateQuarantine(), and setOverloaded() events.",
      "NotificationEmitter Wiring: Fixed dormant NotificationEmitter. It now correctly broadcasts threat.detected, evidence.quarantined, rate_limit.exceeded, and system.panic events.",
      "HoundPool Execution Results: Wired HoundPool.onResult to intercept worker timeouts and errors, converting them into Watcher alerts and system.panic notifications."
    ]
  },
  {
    "version": "1.4.0",
    "date": "2026-02-16",
    "title": "Deterministic Fuzz Assurance Program",
    "summary": "This release finalizes the Jazzer-free deterministic fuzz assurance roadmap for Tracehound core. It adds reproducible property-fuzz coverage, adversarial corpus replay, lifecycle governance, and CI gate enforcement for audit-grade security invariants.",
    "highlights": [
      "Deterministic Property Fuzz Suite under packages/core/tests/fuzz/ for mandatory invariants:",
      "IPC logical safety",
      "Adversarial State-Machine Fuzzing:",
      "Versioned Adversarial Corpus under security/corpus/ with replayable seed manifest."
    ]
  }
]

export const timelineRows: TimelineRow[] = [
  {
    "version": "1.3.0",
    "date": "2026-02-16",
    "title": "Security Model Alignment & Parser Hardening"
  },
  {
    "version": "1.2.0",
    "date": "2026-02-14",
    "title": "Forensic Hardening & English Audit Prep"
  },
  {
    "version": "1.1.0",
    "date": "2026-02-10",
    "title": "Production Hardening (Phase 4 P1)"
  },
  {
    "version": "1.0.0",
    "date": "2024-12-27",
    "title": "Stable Release"
  },
  {
    "version": "0.7.0",
    "date": "v1.0.0 P0 Complete",
    "title": "Release 0.7.0"
  },
  {
    "version": "0.6.0",
    "date": "Production Ready (P0 Complete)",
    "title": "Release 0.6.0"
  },
  {
    "version": "0.5.0",
    "date": "Hound Process Isolation",
    "title": "Release 0.5.0"
  },
  {
    "version": "0.4.0",
    "date": "Observability & Resilience",
    "title": "Release 0.4.0"
  },
  {
    "version": "0.3.0",
    "date": "Core Logic",
    "title": "Release 0.3.0"
  },
  {
    "version": "0.2.0",
    "date": "Evidence & Quarantine",
    "title": "Release 0.2.0"
  },
  {
    "version": "0.1.0",
    "date": "Foundation",
    "title": "Release 0.1.0"
  }
]
